### ISSUE TITLE
Support comments in tsconfig.json

### ISSUE THREAD

**Issue by sbalay** [frankleng/esbuild-ts-paths#1]
tsconfig.json files usually contain code comments (example: https://github.com/react-native-community/react-native-template-typescript/blob/main/template/tsconfig.json).

However, files with comments generate errors in this plugin:

```
    Details:

    SyntaxError: /Users/user/project/tsconfig.json: Unexpected token / in JSON at position 583
        at parse (<anonymous>)

       8 |       format: 'cjs',
       9 |       target: 'es2020',
    > 10 |       plugins: [tsPaths()],
         |                 ^
      11 |       write: false,
      12 |       bundle: false,
      13 |     })

      at module.exports (node_modules/esbuild-ts-paths/index.js:6:31)
      at Object.process (esbuildJestTransformer.js:10:17)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:620:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:766:40)
      ```

**Comment by frankleng** [comment]
@sbalay didn't realize you can have comments in a json file. but since `tsc` tolerates comments, will fix.
