### ISSUE TITLE
Plugin "esbuild-ts-paths" returned a non-absolute path

### ISSUE THREAD

**Issue by selfagency** [frankleng/esbuild-ts-paths#6]
here's my tsconfig paths:

```
    "paths": {
      "@shared/*": ["../shared/src/*"],
      "@shared": ["../shared/src"]
    },
```

here's my esbuild config:

```js
#!/usr/bin/env node
const esbuild = require('esbuild');
const tsPaths = require('esbuild-ts-paths');

(async () => {
  process.argv.shift();
  process.argv.shift();

  try {
    await esbuild.build({
      bundle: true,
      entryPoints: ['lib/index.ts', 'lib/cli.ts'],
      tsconfig: './tsconfig.json',
      plugins: [tsPaths('./tsconfig.json')],
      platform: 'node',
      outdir: './dist',
      sourcemap: true,
      target: 'node16',
      resolveExtensions: ['.ts', '.tsx', '.js', '.jsx'],
      minify: true,
      external: [
        'newrelic',
        'pg-native',
        'dd-trace',
        '@paypal/checkout-server-sdk',
        'google-gax',
        'jsdom',
      ],
    });
  } catch (err) {
    console.error(err);
  }
})();
```

here's the result:

```shell
$ yarn workspace ud-shared tsc; if test -d 'dist'; then rm -rf dist; fi; ./build.cjs
$ tsc -p .
✘ [ERROR] Plugin "esbuild-ts-paths" returned a non-absolute path: @shared (set a namespace if this is not a file path)

    lib/model/order.ts:25:25:
      25 │ import {RefundType} from '@shared';
         ╵                          ~~~~~~~~~

✘ [ERROR] Plugin "esbuild-ts-paths" returned a non-absolute path: @shared (set a namespace if this is not a file path)

    lib/routes/AdminController.ts:33:25:
      33 │ import {DappStatus} from '@shared';
         ╵                          ~~~~~~~~~

✘ [ERROR] Plugin "esbuild-ts-paths" returned a non-absolute path: @shared (set a namespace if this is not a file path)

    lib/routes/DappController.ts:10:25:
      10 │ import {DappStatus} from '@shared';
         ╵                          ~~~~~~~~~

✘ [ERROR] Plugin "esbuild-ts-paths" returned a non-absolute path: @shared (set a namespace if this is not a file path)

    lib/entities/Dapp.ts:16:25:
      16 │ import {DappStatus} from '@shared';
         ╵                          ~~~~~~~~~

Error: Build failed with 4 errors:
lib/entities/Dapp.ts:16:25: ERROR: Plugin "esbuild-ts-paths" returned a non-absolute path: @shared (set a namespace if this is not a file path)
lib/model/order.ts:25:25: ERROR: Plugin "esbuild-ts-paths" returned a non-absolute path: @shared (set a namespace if this is not a file path)
lib/routes/AdminController.ts:33:25: ERROR: Plugin "esbuild-ts-paths" returned a non-absolute path: @shared (set a namespace if this is not a file path)
lib/routes/DappController.ts:10:25: ERROR: Plugin "esbuild-ts-paths" returned a non-absolute path: @shared (set a namespace if this is not a file path)
    at failureErrorWithLog (/Users/daniel/code/ud/unstoppable-domains-website/node_modules/esbuild/lib/main.js:1599:15)
    at /Users/daniel/code/ud/unstoppable-domains-website/node_modules/esbuild/lib/main.js:1245:28
    at runOnEndCallbacks (/Users/daniel/code/ud/unstoppable-domains-website/node_modules/esbuild/lib/main.js:1030:63)
    at buildResponseToResult (/Users/daniel/code/ud/unstoppable-domains-website/node_modules/esbuild/lib/main.js:1243:7)
    at /Users/daniel/code/ud/unstoppable-domains-website/node_modules/esbuild/lib/main.js:1352:14
    at /Users/daniel/code/ud/unstoppable-domains-website/node_modules/esbuild/lib/main.js:662:9
    at handleIncomingPacket (/Users/daniel/code/ud/unstoppable-domains-website/node_modules/esbuild/lib/main.js:759:9)
    at Socket.readFromStdout (/Users/daniel/code/ud/unstoppable-domains-website/node_modules/esbuild/lib/main.js:629:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
```

**Comment by frankleng** [comment]
@selfagency pushing fix in `1.1.3`. haven't used importing from root of alias. but easy fix
